import { DEFAULT_AUTHOR } from './lib/brand'
import type { CanvasState, ChartConfig, TemplateId } from './types'

/** Gráfico de ejemplo: volumen semanal vs. hipertrofia (pilar fuerza). */
const baseChart: ChartConfig = {
  mode: 'curve',
  title: 'SERIES SEMANALES VS. ESTÍMULO DE HIPERTROFIA',
  min: 0,
  max: 30,
  unit: 'series',
  zone: '10-18',
  zoneLabel: 'VENTANA HIPERTROFIA (10–18 series por músculo)',
  shape: 'bell',
  barLabels: '4, 8, 12, 16, 20, 24',
  barValues: '38, 60, 84, 92, 80, 62',
  gaugeValue: 14,
  gaugeThreshold: 22,
  gaugeLabel: 'Series semanales',
}

/** Cadencia ciclista: queda sólo como preset para posts de ciclismo. */
const cadenceChart: ChartConfig = {
  mode: 'curve',
  title: 'CADENCIA (RPM) VS. EFICIENCIA NEUROMUSCULAR',
  min: 40,
  max: 130,
  unit: 'rpm',
  zone: '70-90',
  zoneLabel: 'Zona óptima de eficiencia neuromuscular (70–90 rpm)',
  shape: 'bell',
  barLabels: '50, 60, 70, 80, 90, 100, 110',
  barValues: '58, 66, 81, 88, 84, 70, 61',
  gaugeValue: 82,
  gaugeThreshold: 95,
  gaugeLabel: 'Cadencia media',
}

export const DEFAULT_STATE: CanvasState = {
  template: 'metric',
  aspect: 'feed',
  headlineFont: 'chakra',
  headlineScale: 100,
  tag: 'BIOENERGÉTICA · GASTO CALÓRICO',
  headlineA: 'UN KILO DE GRASA NO SE QUEMA',
  headlineB: 'EN UNA SESIÓN.',
  body: 'Un kilo de tejido adiposo almacena cerca de 7700 kcal. Ninguna clase de spinning lo borra: lo borra el déficit sostenido semana tras semana.',
  citeMain: 'HALL Y COL., 2012 · THE LANCET',
  citeSub: 'Cuantificación del efecto del desequilibrio energético sobre el peso corporal',
  metricValue: '7700',
  metricLabel: 'KCAL ALMACENADAS EN 1 KG DE GRASA',
  metricAccent: 'orange',
  cardA: { label: 'DOMS ALTO', value: '+14% fuerza', caption: '8 semanas de bloque', accent: 'gray' },
  cardB: { label: 'DOMS BAJO', value: '+14% fuerza', caption: 'mismo bloque, mismo resultado', accent: 'cyan' },
  verdict: 'MISMA GANANCIA. DISTINTO DOLOR.',
  chart: baseChart,
  kicker: 'EL RESULTADO NO SE NEGOCIA. EL MÉTODO, TAMPOCO.',
  manifestoAuthor: DEFAULT_AUTHOR,
  manifestoStyle: 'bar',
  theme: 'dark',
  diagramKind: 'radar',
  diagramAccent: 'blue',
  radarAxes: 'Sueño, Nutrición, Fuerza, Volumen, Estrés, Movilidad',
  radarValues: '45, 70, 85, 90, 30, 50',
  radarCompare: '80, 80, 75, 70, 75, 70',
  radarLabelA: 'Tu semana real',
  radarLabelB: 'Semana equilibrada',
  circleDivisions: '1, 3, 12',
  circleCaptions: 'El objetivo\nLos bloques\nLas semanas\nHoy',
  dominoCount: 7,
  dominoStart: 'Hábito mínimo',
  dominoEnd: 'Resultado masivo',
  curveExpected: 'Ruido',
  curveReal: 'Claridad',
  curveGoal: 'Meta',
  repeatPhrase: 'SI TODO ESTÁ EN TU CONTRA, AVANZÁ EN CONTRA DE TODO',
  repeatAccent: 'white',
  repeatMode: 'diagonal',
  repeatScale: 100,
  repeatLeading: 100,
  repeatCount: 7,
  repeatCenterScale: 140,
  repeatBand: false,
  bgOverlay: 75,
  bgGradient: true,
  bgMono: false,
  floatingPlate: false,
  bgZoom: 100,
  bgX: 0,
  bgY: 0,
  contentAlign: 'auto',
  contentGap: 100,
}

/** Contenido de ejemplo por plantilla (tomado de las placas de referencia). */
export const SAMPLES: Record<TemplateId, Partial<CanvasState>> = {
  metric: {
    tag: 'BIOENERGÉTICA · GASTO CALÓRICO',
    headlineA: 'UN KILO DE GRASA NO SE QUEMA',
    headlineB: 'EN UNA SESIÓN.',
    metricValue: '7700',
    metricLabel: 'KCAL ALMACENADAS EN 1 KG DE GRASA',
    metricAccent: 'orange',
    body: DEFAULT_STATE.body,
    citeMain: DEFAULT_STATE.citeMain,
    citeSub: DEFAULT_STATE.citeSub,
  },
  compare: {
    tag: 'REALIDAD DEL DOMS',
    headlineA: 'SIN DOLOR AL OTRO DÍA NO *FALLÓ* EL',
    headlineB: 'ENTRENO.',
    cardA: DEFAULT_STATE.cardA,
    cardB: DEFAULT_STATE.cardB,
    verdict: 'MISMA GANANCIA. DISTINTO DOLOR.',
    body: 'Las agujetas responden más a lo nuevo que fue el estímulo que a su calidad. Podés progresar perfectamente sin despertarte adolorido.',
    citeMain: 'DAMAS Y COL., 2016 · EUROPEAN JOURNAL OF APPLIED PHYSIOLOGY',
    citeSub: 'DOMS como marcador no confiable de daño muscular y adaptación',
  },
  chart: {
    tag: 'FUERZA · HIPERTROFIA',
    headlineA: 'MÁS SERIES NO ES',
    headlineB: 'MÁS MÚSCULO.',
    chart: baseChart,
    body: 'El estímulo crece con el volumen hasta un punto. Pasada la ventana, sumás fatiga que no se recupera y el progreso se frena.',
    citeMain: 'SCHOENFELD Y COL., 2017 · J SPORTS SCI',
    citeSub: 'Dosis-respuesta entre volumen semanal de entrenamiento e hipertrofia muscular',
  },
  statement: {
    tag: 'NOTA TÁCTICA · FATIGA',
    headlineA: 'NO ES FALTA DE DISCIPLINA. ES TU',
    headlineB: 'SISTEMA NERVIOSO PIDIENDO TREGUA.',
    kicker: 'EMPUJAR EN ESE ESTADO NO ES DISCIPLINA. ES SUMAR DEUDA.',
    body: 'HRV en caída sostenida y frecuencia cardíaca en reposo elevada. Bajá el volumen 48 horas y el rendimiento vuelve solo.',
    citeMain: 'KIVINIEMI Y COL., 2007 · EUROPEAN J. OF APPLIED PHYSIOLOGY',
    citeSub: 'HRV como indicador de fatiga acumulada y readiness de entrenamiento',
  },
  diagram: {
    tag: 'MODELO MENTAL · RECUPERACIÓN',
    headlineA: 'NO TE FALTA FUERZA.',
    headlineB: 'TE SOBRA DESEQUILIBRIO.',
    body: 'Entrenar al 90 % con sueño al 45 % no es disciplina: es una rueda que no gira.',
    citeMain: '',
    citeSub: '',
    diagramKind: 'radar',
  },
  repeat: {
    tag: 'DISCIPLINA Y MÉTODO',
    repeatPhrase: 'SI TODO ESTÁ EN TU CONTRA, AVANZÁ EN CONTRA DE TODO',
  },
  manifesto: {
    tag: 'DISCIPLINA Y MÉTODO',
    headlineA: 'LA MOTIVACIÓN TE HACE EMPEZAR.',
    headlineB: 'EL SISTEMA TE HACE VOLVER.',
    manifestoAuthor: DEFAULT_AUTHOR,
    manifestoStyle: 'bar',
  },
}

/** Presets rápidos del gráfico. */
export const CHART_PRESETS: { label: string; chart: Partial<ChartConfig> }[] = [
  { label: 'Curva · volumen', chart: { ...baseChart } },
  { label: 'Curva · cadencia', chart: { ...cadenceChart } },
  {
    label: 'Curva · lactato',
    chart: {
      mode: 'curve',
      shape: 'rise',
      title: 'LACTATO SANGUÍNEO VS. POTENCIA (W)',
      min: 100,
      max: 400,
      unit: 'W',
      zone: '240-280',
      zoneLabel: 'Zona de umbral: donde se construye la resistencia',
    },
  },
  {
    label: 'Barras · volumen',
    chart: { ...baseChart, mode: 'bars', title: 'ESTÍMULO (%) POR SERIES SEMANALES', min: 0, max: 100, unit: '%', zone: '10-18' },
  },
  {
    label: 'Medidor · HRV',
    chart: {
      mode: 'gauge',
      title: 'HRV DE HOY VS. TU LÍNEA BASE',
      min: 20,
      max: 100,
      unit: 'ms',
      zone: '55-80',
      zoneLabel: 'Rango normal de tu HRV',
      gaugeValue: 41,
      gaugeThreshold: 50,
      gaugeLabel: 'HRV matinal',
    },
  },
]
