import { generateScatter } from './lib/chart'
import type { CanvasState, ChartConfig, TemplateId } from './types'

const baseChart: ChartConfig = {
  mode: 'scatter',
  title: 'CADENCIA (RPM) VS. FUERZA POR PEDALADA',
  scatter: generateScatter(7),
  seriesA: '62, 66, 58, 72, 63, 68, 65',
  seriesALabel: 'Semana normal',
  seriesB: '',
  seriesBLabel: 'Semana de fatiga',
  showZone: true,
  zoneFrom: 45,
  zoneTo: 70,
  zoneLabel: 'Zona óptima de eficiencia neuromuscular (70–90 rpm)',
  showThreshold: false,
  threshold: 35,
  thresholdLabel: 'umbral de alerta',
  showMarker: false,
  marker: 33,
  markerLabel: 'Acá aparece la sed',
  markerSub: '(2% de pérdida de fluidos)',
}

export const DEFAULT_STATE: CanvasState = {
  template: 'metric',
  aspect: 'feed',
  headlineFont: 'chakra',
  headlineScale: 100,
  tag: 'BIOENERGÉTICA · GASTO CALÓRICO',
  headlineA: 'UN KILO DE GRASA NO SE QUEMA',
  headlineB: 'EN UNA SESIÓN.',
  body: 'Un kilo de tejido adiposo almacena cerca de 7700 kcal. Ninguna clase de spinning lo borra: lo borra el déficit sostenido semana tras semana.',
  citeMain: 'HALL Y COL., 2012 · THE LANCET',
  citeSub: 'Cuantificación del efecto del desequilibrio energético sobre el peso corporal',
  metricValue: '7700',
  metricLabel: 'KCAL ALMACENADAS EN 1 KG DE GRASA',
  metricAccent: 'orange',
  cardA: { label: 'DOMS ALTO', value: '+14% fuerza', caption: '8 semanas de bloque', accent: 'gray' },
  cardB: { label: 'DOMS BAJO', value: '+14% fuerza', caption: 'mismo bloque, mismo resultado', accent: 'cyan' },
  verdict: 'MISMA GANANCIA. DISTINTO DOLOR.',
  chart: baseChart,
  kicker: 'EL RESULTADO NO SE NEGOCIA. EL MÉTODO, TAMPOCO.',
}

/** Contenido de ejemplo por plantilla (tomado de las placas de referencia). */
export const SAMPLES: Record<TemplateId, Partial<CanvasState>> = {
  metric: {
    tag: 'BIOENERGÉTICA · GASTO CALÓRICO',
    headlineA: 'UN KILO DE GRASA NO SE QUEMA',
    headlineB: 'EN UNA SESIÓN.',
    metricValue: '7700',
    metricLabel: 'KCAL ALMACENADAS EN 1 KG DE GRASA',
    metricAccent: 'orange',
    body: DEFAULT_STATE.body,
    citeMain: DEFAULT_STATE.citeMain,
    citeSub: DEFAULT_STATE.citeSub,
  },
  compare: {
    tag: 'REALIDAD DEL DOMS',
    headlineA: 'SIN DOLOR AL OTRO DÍA NO *FALLÓ* EL',
    headlineB: 'ENTRENO.',
    cardA: DEFAULT_STATE.cardA,
    cardB: DEFAULT_STATE.cardB,
    verdict: 'MISMA GANANCIA. DISTINTO DOLOR.',
    body: 'Las agujetas responden más a lo nuevo que fue el estímulo que a su calidad. Podés progresar perfectamente sin despertarte adolorido.',
    citeMain: 'DAMAS Y COL., 2016 · EUROPEAN JOURNAL OF APPLIED PHYSIOLOGY',
    citeSub: 'DOMS como marcador no confiable de daño muscular y adaptación',
  },
  chart: {
    tag: 'BIOMECÁNICA APLICADA',
    headlineA: 'CADENCIA ALTA Y BAJA FUERZA.',
    headlineB: 'ESE ES EL ERROR.',
    chart: baseChart,
    body: 'Mashing fatiga tu fuerza rápido. Spinning excesivo satura tu sistema cardiovascular sin aprovechar la fuerza que ya tenés.',
    citeMain: 'LUCÍA Y COL., 2004 · JOURNAL OF APPLIED PHYSIOLOGY',
    citeSub: 'Economía de pedaleo y selección de cadencia en ciclistas entrenados',
  },
  statement: {
    tag: 'NOTA TÁCTICA · FATIGA',
    headlineA: 'NO ES FALTA DE DISCIPLINA. ES TU',
    headlineB: 'SISTEMA NERVIOSO PIDIENDO TREGUA.',
    kicker: 'EMPUJAR EN ESE ESTADO NO ES DISCIPLINA. ES SUMAR DEUDA.',
    body: 'HRV en caída sostenida y frecuencia cardíaca en reposo elevada. Bajá el volumen 48 horas y el rendimiento vuelve solo.',
    citeMain: 'KIVINIEMI Y COL., 2007 · EUROPEAN J. OF APPLIED PHYSIOLOGY',
    citeSub: 'HRV como indicador de fatiga acumulada y readiness de entrenamiento',
  },
}

/** Presets extra del gráfico para las dos placas de curva de referencia. */
export const CHART_PRESETS: { label: string; chart: Partial<ChartConfig> }[] = [
  {
    label: 'Dispersión · cadencia',
    chart: { ...baseChart },
  },
  {
    label: 'Curvas · HRV fatiga',
    chart: {
      mode: 'curve',
      title: 'HRV DIARIO · SEMANA NORMAL VS. SEMANA DE FATIGA',
      seriesA: '62, 66, 58, 72, 63, 68, 65',
      seriesALabel: 'Semana normal',
      seriesB: '56, 47, 41, 35, 30, 25, 22',
      seriesBLabel: 'Semana de fatiga',
      showZone: false,
      showThreshold: true,
      threshold: 38,
      thresholdLabel: 'umbral de alerta',
      showMarker: false,
    },
  },
  {
    label: 'Curva · potencia vs. sed',
    chart: {
      mode: 'curve',
      title: 'POTENCIA SOSTENIDA VS. % DESHIDRATACIÓN',
      seriesA: '100, 98, 94, 88, 80, 72, 65',
      seriesALabel: 'Potencia sostenida',
      seriesB: '',
      showZone: false,
      showThreshold: false,
      showMarker: true,
      marker: 33,
      markerLabel: 'Acá aparece la sed',
      markerSub: '(2% de pérdida de fluidos)',
    },
  },
  {
    label: 'Curva · lactato',
    chart: {
      mode: 'curve',
      title: 'LACTATO SANGUÍNEO (MMOL/L) VS. INTENSIDAD',
      seriesA: '1.1, 1.2, 1.3, 1.5, 1.9, 2.6, 4.0, 6.2, 9.0',
      seriesALabel: 'Lactato',
      seriesB: '',
      showZone: true,
      zoneFrom: 50,
      zoneTo: 72,
      zoneLabel: 'Zona de umbral: donde se construye la resistencia',
      showThreshold: false,
      showMarker: false,
    },
  },
]
